// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJGe4FLccJBkdWFaqiGOoQEUYlAaE_SUI',
    appId: '1:278216846064:web:819ee6b46d54200c567035',
    messagingSenderId: '278216846064',
    projectId: 'fir-sample-290fe',
    authDomain: 'fir-sample-290fe.firebaseapp.com',
    storageBucket: 'fir-sample-290fe.appspot.com',
    measurementId: 'G-8GX2YKDNNL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD70PqPvd_Cu1oauhCV5FO3_G9KzzN8hZY',
    appId: '1:278216846064:android:d9ce8923cdc06e9b567035',
    messagingSenderId: '278216846064',
    projectId: 'fir-sample-290fe',
    storageBucket: 'fir-sample-290fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc4jL3sGjOJDaKqWnQ1PegLK3wYjGxRCU',
    appId: '1:278216846064:ios:4210bbf2b07d7450567035',
    messagingSenderId: '278216846064',
    projectId: 'fir-sample-290fe',
    storageBucket: 'fir-sample-290fe.appspot.com',
    iosClientId: '278216846064-s28o15tcqk6qmoc0fataec0jgpcqct7v.apps.googleusercontent.com',
    iosBundleId: 'com.example.timeWatchApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc4jL3sGjOJDaKqWnQ1PegLK3wYjGxRCU',
    appId: '1:278216846064:ios:4210bbf2b07d7450567035',
    messagingSenderId: '278216846064',
    projectId: 'fir-sample-290fe',
    storageBucket: 'fir-sample-290fe.appspot.com',
    iosClientId: '278216846064-s28o15tcqk6qmoc0fataec0jgpcqct7v.apps.googleusercontent.com',
    iosBundleId: 'com.example.timeWatchApp',
  );
}
